FROM golang:1.9-alpine
RUN apk add -U git
COPY . /go/src/github.com/gl-prototypes/jq-cmd
WORKDIR /go/src/github.com/gl-prototypes/jq-cmd/cmd/jqserve
RUN go get github.com/gliderlabs/ssh
RUN go get github.com/gliderlabs/com
RUN go get github.com/spf13/viper
RUN go get github.com/thejerf/suture
RUN go build
CMD ["cat", "/go/src/github.com/gl-prototypes/jq-cmd/cmd/jqserve/jqserve"]
