apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jq-cmd
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: jq-cmd
    spec:
      volumes:
        - name: hostkey
          secret:
            secretName: jq-cmd
            items:
            - key: hostkey
              path: hostkey
      containers:
        - name: jq
          image: us.gcr.io/gliderlabs/jq-cmd:latest
          ports:
            - name: ssh
              containerPort: 2222
          volumeMounts:
            - mountPath: /tmp/
              name: hostkey
---
kind: Service
apiVersion: v1
metadata:
  name: jq-cmd
spec:
  type: LoadBalancer
  selector:
    app: jq-cmd
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
